# Generated by Django 5.2.8 on 2025-11-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('apartamentoID', models.AutoField(db_column='PK_apartamentoID', primary_key=True, serialize=False)),
                ('numeroApartamento', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'APARTAMENTO',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('comprobanteID', models.AutoField(db_column='PK_comprobanteID', primary_key=True, serialize=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(db_column='FK_apartamentoID', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='pagoprop.apartamento')),
                ('copropietario', models.ForeignKey(db_column='FK_copropietarioID', on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'COMPROBANTE',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PropietarioApartamento',
            fields=[
                ('propietarioAptoID', models.AutoField(db_column='PK_propietarioAptoID', primary_key=True, serialize=False)),
                ('apartamento', models.ForeignKey(db_column='FK_apartamentoID', on_delete=django.db.models.deletion.CASCADE, related_name='propietario_apartamentos', to='pagoprop.apartamento')),
                ('copropietario', models.ForeignKey(db_column='FK_copropietarioID', on_delete=django.db.models.deletion.CASCADE, related_name='propietario_apartamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PROPIETARIO_APARTAMENTO',
                'unique_together': {('copropietario', 'apartamento')},
            },
        ),
    ]
