# Generated by Django 5.2.8 on 2025-11-10 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoprop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='copropietarios',
            field=models.ManyToManyField(related_name='apartamentos', through='pagoprop.PropietarioApartamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
