# Generated by Django 5.2.8 on 2025-11-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoprop', '0002_apartamento_copropietarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='archivo',
            field=models.FileField(upload_to='comprobantes/'),
        ),
    ]
